<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_kasirAja</name>
   <tag></tag>
   <elementGuidId>134151d1-4b31-485d-bc98-8e6bdd7d4ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.chakra-heading.css-1wswht5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[(text() = 'kasirAja' or . = 'kasirAja')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6f7e8b3e-8ca1-4a27-8e2f-1111ba34c4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-heading css-1wswht5</value>
      <webElementGuid>8fd240ee-2dfe-4ae3-90c6-b1516cc04d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kasirAja</value>
      <webElementGuid>039a495f-ad1e-49d0-87cb-2ad7e31c877f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-tnxwfz&quot;]/div[@class=&quot;chakra-stack css-owjkmg&quot;]/h3[@class=&quot;chakra-heading css-1wswht5&quot;]</value>
      <webElementGuid>55b19669-1333-4dcd-880d-951f410b9431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/h3</value>
      <webElementGuid>938c08e7-c119-41fd-b146-1ee5b47087a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dashboard'])[1]/preceding::h3[1]</value>
      <webElementGuid>da43e948-5015-45c1-8d3d-e9b8b8283195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kasir'])[1]/preceding::h3[1]</value>
      <webElementGuid>fcfaad14-c1d0-4819-9476-76b4e7baacc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>75bca9ba-485e-4dbe-b60b-d99b8a65b868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'kasirAja' or . = 'kasirAja')]</value>
      <webElementGuid>eb18803c-a218-400a-a1c7-b14ca8173b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
