<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_kategori</name>
   <tag></tag>
   <elementGuidId>8097bddb-a42d-4e3b-874e-45d35bab6190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.chakra-heading.css-18j379d > a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/categories' and (text() = '/ kategori  ' or . = '/ kategori  ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8748c2f3-14dc-4bf5-90ab-5f5164752d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categories</value>
      <webElementGuid>da500a9d-89fb-4701-974f-d2adad674f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/ kategori  </value>
      <webElementGuid>c2001fab-2542-4eaa-b293-ec9e227bfab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1r35f0l&quot;]/div[@class=&quot;chakra-container css-9rmdie&quot;]/div[@class=&quot;css-tyo1sz&quot;]/h2[@class=&quot;chakra-heading css-18j379d&quot;]/a[2]</value>
      <webElementGuid>38088f81-ac60-4afc-938a-cbf5cb4e7ddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/h2/a[2]</value>
      <webElementGuid>35849499-95f9-4598-80d5-df3bde32177c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dashboard'])[2]/following::a[1]</value>
      <webElementGuid>11e67dfe-80a1-4240-a382-424904dc51bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nama'])[1]/preceding::a[1]</value>
      <webElementGuid>9e0ff91b-12ab-4b74-b1b2-eb3f6886ef8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='deskripsi'])[1]/preceding::a[1]</value>
      <webElementGuid>eabedffd-8440-4242-bc91-ffb953366d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/']/parent::*</value>
      <webElementGuid>5d720b54-0c7b-44fd-ae99-32e28d35adff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/categories')])[2]</value>
      <webElementGuid>bbda4a87-f944-4491-941f-bb46704f438f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a[2]</value>
      <webElementGuid>22b35ad0-e055-4228-9695-f8b614c05981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/categories' and (text() = '/ kategori  ' or . = '/ kategori  ')]</value>
      <webElementGuid>379257fd-2c2f-4e01-91cc-b8359d92c212</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
