<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn tambah</name>
   <tag></tag>
   <elementGuidId>df975839-8665-4c96-baf0-c15e46ff0998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.chakra-button.css-1piskbq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/categories/create' and (text() = 'tambah' or . = 'tambah')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7ab08b3-5f8e-45ed-aeb9-dc57f2adebbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1piskbq</value>
      <webElementGuid>c64d1be2-3ba5-447c-bae4-93b00944f9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categories/create</value>
      <webElementGuid>39371b03-5801-448e-88b3-04a243c638ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tambah</value>
      <webElementGuid>f4a49146-4453-4406-aa9c-ab592886cd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1r35f0l&quot;]/div[@class=&quot;chakra-container css-9rmdie&quot;]/div[@class=&quot;css-1t33j5j&quot;]/a[@class=&quot;chakra-button css-1piskbq&quot;]</value>
      <webElementGuid>d5a7fdec-2cb0-4bf8-bf5a-e58868d903ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>188eaad2-6240-46d8-9b6c-4494e37ddb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'tambah')]</value>
      <webElementGuid>7ddf1d19-e616-4d6c-b812-b6a33fa8fb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dashboard'])[2]/following::a[2]</value>
      <webElementGuid>11ed4847-7f5e-4bf3-915c-dfb2b5746d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nama'])[1]/preceding::a[1]</value>
      <webElementGuid>04e5a3cc-b262-47ec-93de-f814f2f01a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='deskripsi'])[1]/preceding::a[1]</value>
      <webElementGuid>062eafb7-d0f3-41d8-9325-dc4ffe073ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tambah']/parent::*</value>
      <webElementGuid>58317759-f4ea-48bf-be79-abf81ae1aece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/categories/create')]</value>
      <webElementGuid>45d84615-b36e-436b-bf0b-93fa406fe60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>f419c460-5d2c-4294-81f4-71b834f823cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/categories/create' and (text() = 'tambah' or . = 'tambah')]</value>
      <webElementGuid>7ef75b5e-1009-4006-87d1-faa64d98fc27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
