<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dashboard   kategori</name>
   <tag></tag>
   <elementGuidId>d387bcd9-15e7-4274-bc58-4258252b2f78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-tyo1sz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'dashboard  / kategori  ' or . = 'dashboard  / kategori  ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20eb0eb7-0316-4623-9000-ae0fdb45a061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-tyo1sz</value>
      <webElementGuid>8402248f-2635-4e7b-8a01-eda7e3d67237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dashboard  / kategori  </value>
      <webElementGuid>2350e4a8-510f-4d16-b951-cfc7ea7053ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1r35f0l&quot;]/div[@class=&quot;chakra-container css-9rmdie&quot;]/div[@class=&quot;css-tyo1sz&quot;]</value>
      <webElementGuid>a3bc319a-3980-4451-bd28-ada78976be1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div</value>
      <webElementGuid>6d5a3836-8583-415a-b604-860e865ca306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/following::div[2]</value>
      <webElementGuid>0a63969c-55a4-4b6d-bfbb-75a0b0373e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zuzu_shop'])[1]/following::div[2]</value>
      <webElementGuid>a8b923d0-914b-4fd0-8333-e6b094e6908a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>a3e0a29d-6e01-43b8-815f-14c77e2b7cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'dashboard  / kategori  ' or . = 'dashboard  / kategori  ')]</value>
      <webElementGuid>e2e5106b-88e6-4574-84e5-7ea4476838af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
